<!--
README 模板文件
这个文件会被 devpocket 读取，然后替换变量生成 README.md

支持变量：
{{name}}        项目名称
{{description}} 项目描述
{{license}}     许可证
-->

<!-- 项目标题 -->
# {{name}}

<!-- 项目简介 -->
{{description}}

---

<!-- 安装说明 -->
## Installation

```bash
npm install

<!-- 使用说明 -->
## Usage

```bash
npm start

<!-- 项目结构（可选说明） --> 
<!-- 你可以在这里描述项目目录结构 例如： src/ bin/ templates/ -->
<!-- 许可证 -->
License
{{license}}

<!-- 生成说明 --> 
<!-- This README was generated by devpocket. -->
---

### 模板变量说明

| 变量 | 含义 |
|---|---|
| `{{name}}` | 项目名称 |
| `{{description}}` | 项目描述 |
| `{{license}}` | 许可证 |

---

### devpocket 生成后的 README 示例

假设输入：
name: my-app
description: my first project
license: MIT

生成：

```md
# my-app

my first project

## Installation

npm install

## Usage

npm start

## License

MIT